# Generated by Django 4.1.7 on 2023-03-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_faculty_subjects_batch"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
